// Board color data from Python bco.py
export const PROPERTY_COLORS = {
  // Layer 1 - Outer edge properties
  C1A: '#BAD191',
  C1B: '#C7CCE3',
  C1C: '#71EDE1',
  C1D: '#FFF24F',
  C1E: '#F46A95',
  C1F: '#F0F7D5',
  C1G: '#97FF8F',
  C1H: '#AC9FFB',
  // Layer 2
  C2A: '#C98FCF',
  C2B: '#9A7340',
  C2C: '#F2BC6C',
  C2D: '#D6F2EF',
  C2E: '#14BC3C',
  C2F: '#5FB7FE',
  C2G: '#FFB3FF',
  C2H: '#F59469',
  // Layer 3 - Inner circle
  C3A: '#B4D200',
  C3B: '#6CFCDA',
  C3C: '#FFB92D',
  C3D: '#FF5DBA',
} as const;

// Board layout constants
export const BOARD_COLORS = {
  BROWN: '#8B4513',
  OUTL: '#8B4513',
  CO1: '#FFFFFF',
  CCH: 'lightpink',  // Tax spaces
  CKV: 'gold',       // Card spaces
  CVX: 'lightblue',  // Special spaces
} as const;

// Space codes in order (from Python banco_kihieu_o)
export const BANCO_KIHIEU_O = [
  '','','',
  '','','',
  '','','',
  '','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '','','',
  '',
  '2A1','2A2',
  'TTN','1R1A','2B1',
  '2B2','2B3','2C1',
  '2U1','2C2','2C3',
  '2R1','2D1','2D2',
  '2D3','2E1','2E2',
  '2E3','1R2A','2F1',
  '2F2','2U2','2F3',
  '2G1','2G2','2G3',
  '2R2','2H1','TXX',
  '2H2','','',
  // '3B3','3B2','3B1',
  // 'DH','2R2A','3A3',
  // '3A2','3D3','HT',
  // '3U2','3A1','3C2',
  // '3C3','2R1A','3D1',
    '','','',
  '','','',
  '','','',
   '','','',
  '','','',
];

// Special spaces (from Python o_dacbiet_kihieu and o_dacbiet_ten)
export const SPECIAL_SPACES: Record<string, string> = {
  // 'DGIA': 'Đấu\nGiá',
  // 'QSN': 'Quà\nSinh Nhật',
  // 'TTN': 'Thuế\nThu\nNhập',
  // 'TXX': 'Thuế\nXa Xỉ',
  // 'DH': 'Đảo\nHướng',
  // 'HT': 'Hoàn\nThuế',
  // '1R1A': 'Ga\nTàu',
  // '1R2A': 'Ga\nTàu',
  // '2R1A': 'Ga\nTàu',
  // '2R2A': 'Ga\nTàu',
  // 'TCQL': 'Trò Chơi\nQuyền Lực',
  // 'THUONG': 'THƯỞNG',
  // 'GDCP': 'Giao Dịch\nCổ Phần',
  // 'DH1': 'Đường\nHầm',
  // 'DH2': 'Đường\nHầm',
  // 'BDX': 'Bãi Đậu Xe\nMiễn Phí',
  // 'LAC3': 'Lắc 3',
  // 'BD': 'BẮT ĐẦU',
  // 'OT': 'Ở tù',
  // 'TT1': 'Thăm',
  // 'TT2': 'Tù',
  // 'NTT': 'NGÀY\nTRẢ TIỀN',
  'VT': 'Vào Tù',
  // 'TDN': 'Tàu Điện\nNgầm',
};

// Property data - properties that have names and prices
export const PROPERTY_DATA: Record<string, { name: string; price: number }> = {
  // '1A1': { name: 'NGUYỄN DU', price: 30 },
  // '1A2': { name: 'NGUYỄN LỮ', price: 30 },
  // '1A3': { name: 'NGUYỄN NHẠC', price: 60 },
  // '1B1': { name: 'KIM ĐỒNG', price: 90 },
  // '1B2': { name: 'ĐINH TIÊN HOÀNG', price: 90 },
  // '1B3': { name: 'XUÂN THUỶ', price: 120 },
  // '1B4': { name: 'CAO THẮNG', price: 120 },
  // '1C1': { name: 'NGUYỄN HỮU THỌ', price: 150 },
  // '1C2': { name: 'XÔ VIẾT NGHỆ TĨNH', price: 150 },
  // '1C3': { name: 'TÔN ĐẢN', price: 180 },
  // '1C4': { name: 'TRẦN CAO VÂN', price: 180 },
  // '1D1': { name: 'TRƯNG NỮ VƯƠNG', price: 210 },
  // '1D2': { name: 'LÊ DUẨN', price: 210 },
  // '1D3': { name: 'DUY TÂN', price: 240 },
  // '1D4': { name: 'BẠCH ĐẰNG', price: 240 },
  // '1E1': { name: 'HÀM NGHI', price: 270 },
  // '1E2': { name: 'HOÀNG DIỆU', price: 270 },
  // '1E3': { name: 'ÔNG ÍCH ĐƯỜNG', price: 300 },
  // '1E4': { name: 'ÔNG ÍCH KHIÊM', price: 300 },
  // '1F1': { name: 'NGUYỄN BỈNH KHIÊM', price: 330 },
  // '1F2': { name: 'NGUYỄN ĐÌNH CHIỂU', price: 330 },
  // '1F3': { name: 'NGUYỄN THỊ ĐỊNH', price: 360 },
  // '1F4': { name: 'ĐIỆN BIÊN PHỦ', price: 360 },
  // '1G1': { name: 'PHAN BỘI CHÂU', price: 390 },
  // '1G2': { name: 'NGUYỄN KHUYẾN', price: 390 },
  // '1G3': { name: 'PHAN CHÂU TRINH', price: 420 },
  // '1G4': { name: 'LÊ QUÝ ĐÔN', price: 420 },
  // '1H1': { name: 'TRẦN HƯNG ĐẠO', price: 450 },
  // '1H2': { name: 'VÕ NGUYÊN GIÁP', price: 480 },
  // '1H3': { name: 'NGUYỄN ÁI QUỐC', price: 510 },
  '2A1': { name: 'NGUYỄN HUỆ', price: 60 },
  '2A2': { name: 'LÊ LỢI', price: 80 },
  '2B1': { name: 'LƯƠNG ĐỊNH CỦA', price: 100 },
  '2B2': { name: 'VÕ THỊ SÁU', price: 100 },
  '2B3': { name: 'HAI BÀ TRƯNG', price: 120 },
  '2C1': { name: 'NGUYỄN TẤT THÀNH', price: 140 },
  '2C2': { name: 'NGUYỄN TRÃI', price: 140 },
  '2C3': { name: 'AN DƯƠNG VƯƠNG', price: 160 },
  '2D1': { name: 'HẬU GIANG', price: 180 },
  '2D2': { name: 'HÙNG VƯƠNG', price: 180 },
  '2D3': { name: 'HUỲNH TẤN PHÁT', price: 200 },
  '2E1': { name: 'PHẠM THỂ HIỂN', price: 220 },
  '2E2': { name: 'KHA VẠNG CÂN', price: 220 },
  '2E3': { name: 'NGUYỄN TRI PHƯƠNG', price: 240 },
  '2F1': { name: 'LÊ ĐẠI HÀNH', price: 260 },
  '2F2': { name: 'TRƯỜNG CHINH', price: 260 },
  '2F3': { name: 'HOÀNG VĂN THỤ', price: 280 },
  '2G1': { name: 'CỘNG HOÀ', price: 300 },
  '2G2': { name: 'NGUYỄN KIỆM', price: 300 },
  '2G3': { name: 'QUANG TRUNG', price: 320 },
  '2H1': { name: 'LUỸ BÁN BÍCH', price: 350 },
  '2H2': { name: 'TÂN KỲ TÂN QUÝ', price: 400 },
  // '3A1': { name: 'PHẠM NGỌC MẬU', price: 130 },
  // '3A2': { name: 'ĐỖ ĐỨC DỤC', price: 130 },
  // '3A3': { name: 'TRẦN THÁI TÔNG', price: 150 },
  // '3B1': { name: 'HÀ HUY TẬP', price: 210 },
  // '3B2': { name: 'NGÔ QUYỀN', price: 210 },
  // '3B3': { name: 'LÊ TRỌNG TẤN', price: 250 },
  // '3C1': { name: 'NGUYỄN THỊ MINH KHAI', price: 330 },
  // '3C2': { name: 'PHAN XÍCH LONG', price: 330 },
  // '3C3': { name: 'HOÀNG THỊ LOAN', price: 380 },
  // '3D1': { name: 'NGUYỄN SINH SẮC', price: 430 },
  // '3D2': { name: 'NGUYỄN LƯƠNG BẰNG', price: 430 },
  // '3D3': { name: 'TÔN ĐỨC THẮNG', price: 500 },
  // '1R1': { name: 'ĐƯỜNG SẮT HÀ NỘI', price: 200 },
  // '1R2': { name: 'ĐƯỜNG SẮT SÀI GÒN', price: 200 },
  '2R1': { name: 'ĐƯỜNG SẮT HẢI PHÒNG', price: 200 },
  '2R2': { name: 'ĐƯỜNG SẮT ĐÀ NẴNG', price: 200 },
  // '1U1': { name: 'TRUYỀN HÌNH CÁP', price: 150 },
  // '1U2': { name: 'NHÀ C.CẤP D.VỤ MẠNG', price: 150 },
  // '1U3': { name: 'CÔNG TY RÁC THẢI', price: 150 },
  // '1U4': { name: 'HỆ THỐNG NƯỚC THẢI', price: 150 },
  '2U1': { name: 'CÔNG TY ĐIỆN LỰC', price: 150 },
  '2U2': { name: 'CÔNG TY CẤP NƯỚC', price: 150 },
  // '3U1': { name: 'CÔNG TY ĐIỆN THOẠI', price: 150 },
  // '3U2': { name: 'CÔNG TY KHÍ ĐỐT', price: 150 },
  // '1T1': { name: 'CTY TAXI MAI LINH', price: 300 },
  // '1T2': { name: 'CTY TAXI HÀ ĐÔNG', price: 300 },
  // '1T3': { name: 'CTY TAXI GRAB', price: 300 },
  // '1T4': { name: 'CTY TAXI TIÊN SA', price: 300 },
};
