dataset_path: ../datasets/s7dataset-2-dice-detection
num_workers: 4

colored: False

tasks:
  dice_detection:
    training_output_path: output/dice_detection/model.keras
    tflite_output_path: output/dice_detection/model.tflite
    inference_path: models/dice_detection/model.tflite
    batch_size: 8
    epochs: 50
    image_resolution: [640, 480]

  dice_score:
    training_output_path: output/dice_score/model.keras
    tflite_output_path: output/dice_score/model.tflite
    inference_path: models/dice_score/model.tflite
    batch_size: 32
    epochs: 50
    image_resolution: [32, 32]

  frame_detection:
    similarity_threshold: 0.5
    qualified_consecutive_frames: 2
