dataset_path: ../datasets/s7dataset-2-dice-detection
num_workers: 4

colored: False

use_random: False

tasks:
  dice_detection:
    inference_path: models/dice_detection/model.tflite
    train_dataset_repeat: 1
    val_dataset_repeat: 1
    batch_size: 16
    epochs: 30
    image_resolution: [640, 480]

  dice_score:
    inference_path: models/dice_score/model.tflite
    batch_size: 32
    train_dataset_repeat: 2
    val_dataset_repeat: 2
    epochs: 5
    image_resolution: [32, 32]

  frame_detection:
    similarity_threshold: 0.5
    qualified_consecutive_frames: 2
